# Generated by Django 4.2.7 on 2025-02-11 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_alter_employee_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emergency_phone',
        ),
        migrations.AlterField(
            model_name='employee',
            name='address_number',
            field=models.CharField(blank=True, help_text='Número de la casa o departamento', max_length=10, null=True, verbose_name='Número de residencia'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address_street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle de residencia'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.education', verbose_name='Nivel de educación'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estatura en metros', max_digits=3, null=True, verbose_name='Estatura'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='knowledge',
            field=models.TextField(blank=True, help_text='Conocimientos y experiencia del empleado', null=True, verbose_name='Conocimientos'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='employees.language', verbose_name='Idiomas'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.maritalstatus', verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='municipality',
            field=models.ForeignKey(blank=True, help_text='Municipio de residencia', null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.municipality', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.neighborhood', verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='postal_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.TextField(blank=True, help_text='Habilidades y destrezas del empleado', null=True, verbose_name='Habilidades'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kilogramos', max_digits=5, null=True, verbose_name='Peso'),
        ),
    ]
